name: Our Workflow
on : push
jobs : 
  cache:
    runs-on : ubuntu-latest
    steps :
      - uses : actions/checkout@v3
      - uses : actions/cache@v3
        with :
          path : ~/.npm
          key : ${{runner.os}}-node-${{hashFile('**/package-lock.json')}}
      - run : npm ci
